import AssignmentTurnedInRoundedIcon from '@mui/icons-material/AssignmentTurnedInRounded'
import DraftsRoundedIcon from '@mui/icons-material/DraftsRounded'
import FactCheckRoundedIcon from '@mui/icons-material/FactCheckRounded'
import SendRoundedIcon from '@mui/icons-material/SendRounded'

export const TRACKING_ROWS_STORAGE_KEY = 'fichesTrackingRows'
export const FICHE_FORMS_STORAGE_KEY = 'fichesFormStates'
export const FICHE_NOTIFICATIONS_STORAGE_KEY = 'fichesNotifications'

export const ficheTemplates = [
  {
    id: 'fiche-besoins-standard',
    name: "Fiche d'expression des besoins en formation",
    version: '2026',
    description: 'Modele standardise utilise par la DDRH pour le recensement des besoins.',
    sections: [
      {
        title: 'Responsable',
        fields: [
          'Nom',
          'Prenom',
          'Fonction',
          'Direction',
        ],
      },
      {
        title: 'Employe',
        fields: ['Matricule', 'Nom', 'Prenom', 'Fonction', 'Direction'],
      },
      {
        title: 'Formation',
        fields: [
          'Intitule de la formation',
          'Contexte de la formation',
        ],
      },
      {
        title: 'Objectifs',
        fields: ['Objectif', 'KPI / Indicateurs de performance', 'Echeance'],
      },
      {
        title: 'Ecarts de competence',
        fields: ['Ecart metier', 'Ecart outils', 'Ecart comportement', 'Ecart projet'],
      },
      {
        title: 'Validation',
        fields: [
          'Echeance',
          'Date de signature',
          'Signature du responsable',
        ],
      },
    ],
  },
]

export const structureRecipients = [
  {
    id: 'ddrh-est',
    structure: 'Direction Est',
    manager: 'Nadia Ferhat',
    email: 'n.ferhat@mobilis.dz',
  },
  {
    id: 'ddrh-ouest',
    structure: 'Direction Ouest',
    manager: 'Karim Ziani',
    email: 'k.ziani@mobilis.dz',
  },
  {
    id: 'audit-interne',
    structure: 'Audit interne',
    manager: 'Samir Touati',
    email: 's.touati@mobilis.dz',
  },
  {
    id: 'formation-centre',
    structure: 'Centre Formation',
    manager: 'Mourad Boussouf',
    email: 'm.boussouf@mobilis.dz',
  },
  {
    id: 'direction-commerciale',
    structure: 'Direction Commerciale',
    manager: 'Imane Rahal',
    email: 'i.rahal@mobilis.dz',
  },
  {
    id: 'direction-si',
    structure: 'Direction SI',
    manager: 'Yasmine Benaissa',
    email: 'y.benaissa@mobilis.dz',
  },
  {
    id: 'direction-finance',
    structure: 'Direction Finance',
    manager: 'Amine Kaci',
    email: 'a.kaci@mobilis.dz',
  },
  {
    id: 'direction-rh',
    structure: 'Direction RH',
    manager: 'Lina Hadef',
    email: 'l.hadef@mobilis.dz',
  },
]

export const trackingStats = [
  {
    title: 'Fiches envoyees',
    value: '18',
    subtitle: 'Campagne en cours',
    background: 'linear-gradient(135deg, #0ea55b 0%, #34d399 100%)',
    Icon: SendRoundedIcon,
  },
  {
    title: 'Notifications lues',
    value: '14',
    subtitle: 'Responsables informes',
    background: 'linear-gradient(135deg, #2563eb 0%, #60a5fa 100%)',
    Icon: DraftsRoundedIcon,
  },
  {
    title: 'Fiches en cours',
    value: '7',
    subtitle: 'Remplissage engage',
    background: 'linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)',
    Icon: FactCheckRoundedIcon,
  },
  {
    title: 'Fiches completees',
    value: '8',
    subtitle: 'Pretes pour validation',
    background: 'linear-gradient(135deg, #7c3aed 0%, #a78bfa 100%)',
    Icon: AssignmentTurnedInRoundedIcon,
  },
]

export const initialTrackingRows = [
  {
    id: 'trk-001',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'ddrh-est',
    structure: 'Direction Est',
    manager: 'Nadia Ferhat',
    sentAt: '18/04/2026',
    status: 'Envoyee',
    notificationStatus: 'Non notifie',
    formStatus: 'Non ouverte',
    reopened: false,
  },
  {
    id: 'trk-002',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'ddrh-ouest',
    structure: 'Direction Ouest',
    manager: 'Karim Ziani',
    sentAt: '18/04/2026',
    status: 'Consultee',
    notificationStatus: 'Notifie',
    formStatus: 'Brouillon',
    reopened: false,
  },
  {
    id: 'trk-003',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'audit-interne',
    structure: 'Audit interne',
    manager: 'Samir Touati',
    sentAt: '17/04/2026',
    status: 'En cours',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-004',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'formation-centre',
    structure: 'Centre Formation',
    manager: 'Mourad Boussouf',
    sentAt: '17/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-005',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'direction-commerciale',
    structure: 'Direction Commerciale',
    manager: 'Imane Rahal',
    sentAt: '16/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-006',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'direction-si',
    structure: 'Direction SI',
    manager: 'Yasmine Benaissa',
    sentAt: '16/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-007',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'direction-finance',
    structure: 'Direction Finance',
    manager: 'Amine Kaci',
    sentAt: '15/04/2026',
    status: 'Consultee',
    notificationStatus: 'Notifie',
    formStatus: 'Brouillon',
    reopened: false,
  },
  {
    id: 'trk-008',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'direction-rh',
    structure: 'Direction RH',
    manager: 'Lina Hadef',
    sentAt: '15/04/2026',
    status: 'En cours',
    notificationStatus: 'Notifie',
    formStatus: 'Brouillon',
    reopened: true,
  },
  {
    id: 'trk-009',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'ddrh-est',
    structure: 'Direction Est',
    manager: 'Nadia Ferhat',
    sentAt: '14/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-010',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'ddrh-ouest',
    structure: 'Direction Ouest',
    manager: 'Karim Ziani',
    sentAt: '14/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
  {
    id: 'trk-011',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'audit-interne',
    structure: 'Audit interne',
    manager: 'Samir Touati',
    sentAt: '13/04/2026',
    status: 'Envoyee',
    notificationStatus: 'Replanifie',
    formStatus: 'Non ouverte',
    reopened: false,
  },
  {
    id: 'trk-012',
    templateId: 'fiche-besoins-standard',
    templateName: "Fiche d'expression des besoins en formation",
    recipientId: 'direction-commerciale',
    structure: 'Direction Commerciale',
    manager: 'Imane Rahal',
    sentAt: '13/04/2026',
    status: 'Completee',
    notificationStatus: 'Notifie',
    formStatus: 'Soumise',
    reopened: false,
  },
]

export const initialFormStates = {
  'trk-002': {
    responsableNom: 'Ziani',
    responsablePrenom: 'Karim',
    responsableFonction: 'Responsable formation',
    responsableDirection: 'Direction Ouest',
    employeMatricule: 'M-2451',
    employeNom: 'Sahnoune',
    employePrenom: 'Riad',
    employeFonction: 'Chef de secteur',
    employeDirection: 'Direction Ouest',
    intituleFormation: 'Leadership',
    contexteFormation: "Montée en responsabilité de plusieurs chefs d'équipe terrain.",
    objectif: 'Renforcer le pilotage des equipes et la prise de decision.',
    kpi: 'Amelioration du taux de pilotage des activites regionales.',
    echeance: '2026-06-15',
    ecartMetier: 'Pilotage des equipes distribuees.',
    ecartOutils: 'Suivi des reportings regionaux.',
    ecartComportement: 'Communication managériale.',
    ecartProjet: '',
    dateSignature: '2026-04-18',
    signatureResponsable: 'Karim Ziani',
  },
  'trk-003': {
    responsableNom: 'Touati',
    responsablePrenom: 'Samir',
    responsableFonction: 'Responsable audit',
    responsableDirection: 'Audit interne',
    employeMatricule: 'A-1184',
    employeNom: 'Belaid',
    employePrenom: 'Sofiane',
    employeFonction: 'Auditeur',
    employeDirection: 'Audit interne',
    intituleFormation: 'Cybersecurite',
    contexteFormation: "Renforcement des controles numeriques et des audits sur les acces sensibles.",
    objectif: 'Mieux identifier les risques cyber et les incidents critiques.',
    kpi: 'Reduction des ecarts de conformite de securite.',
    echeance: '2026-05-20',
    ecartMetier: 'Analyse des vulnerabilites.',
    ecartOutils: 'Utilisation des tableaux de supervision.',
    ecartComportement: 'Culture du signalement.',
    ecartProjet: 'Projet de controle interne 2026.',
    dateSignature: '2026-04-17',
    signatureResponsable: 'Samir Touati',
  },
  'trk-004': {
    responsableNom: 'Boussouf',
    responsablePrenom: 'Mourad',
    responsableFonction: 'Responsable catalogue',
    responsableDirection: 'Centre Formation',
    employeMatricule: 'F-0312',
    employeNom: 'Hamdi',
    employePrenom: 'Nora',
    employeFonction: 'Chargee formation',
    employeDirection: 'Centre Formation',
    intituleFormation: 'Leadership',
    contexteFormation: "Besoin d'accompagner les coordinateurs de formation dans l'animation des sessions.",
    objectif: 'Structurer la conduite des sessions et le management fonctionnel.',
    kpi: 'Satisfaction des participants et taux de completion.',
    echeance: '2026-07-10',
    ecartMetier: 'Animation de groupe.',
    ecartOutils: 'Reporting de formation.',
    ecartComportement: 'Leadership transversal.',
    ecartProjet: '',
    dateSignature: '2026-04-17',
    signatureResponsable: 'Mourad Boussouf',
  },
  'trk-005': {
    responsableNom: 'Rahal',
    responsablePrenom: 'Imane',
    responsableFonction: 'Directrice commerciale',
    responsableDirection: 'Direction Commerciale',
    employeMatricule: 'C-5520',
    employeNom: 'Mebarki',
    employePrenom: 'Lina',
    employeFonction: 'Manager agence',
    employeDirection: 'Direction Commerciale',
    intituleFormation: 'Communication efficace',
    contexteFormation: 'Harmonisation du discours commercial sur les nouvelles offres.',
    objectif: 'Mieux structurer les entretiens clients et le feedback equipe.',
    kpi: 'Hausse du taux de transformation commercial.',
    echeance: '2026-08-05',
    ecartMetier: 'Conduite d’entretien.',
    ecartOutils: 'Argumentaires digitaux.',
    ecartComportement: 'Communication assertive.',
    ecartProjet: '',
    dateSignature: '2026-04-16',
    signatureResponsable: 'Imane Rahal',
  },
  'trk-006': {
    responsableNom: 'Benaissa',
    responsablePrenom: 'Yasmine',
    responsableFonction: 'Directrice SI',
    responsableDirection: 'Direction SI',
    employeMatricule: 'SI-4410',
    employeNom: 'Khadraoui',
    employePrenom: 'Walid',
    employeFonction: 'Ingenieur systeme',
    employeDirection: 'Direction SI',
    intituleFormation: 'Cybersecurite',
    contexteFormation: 'Montée des incidents liés aux accès et aux configurations cloud.',
    objectif: 'Renforcer les competences sur la prevention et la reponse aux incidents.',
    kpi: 'Baisse du temps moyen de traitement des incidents.',
    echeance: '2026-05-28',
    ecartMetier: 'Response incident.',
    ecartOutils: 'SIEM et supervision.',
    ecartComportement: 'Reflexes d’escalade.',
    ecartProjet: 'Programme cloud 2026.',
    dateSignature: '2026-04-16',
    signatureResponsable: 'Yasmine Benaissa',
  },
  'trk-007': {
    responsableNom: 'Kaci',
    responsablePrenom: 'Amine',
    responsableFonction: 'Directeur finance',
    responsableDirection: 'Direction Finance',
    employeMatricule: 'FIN-2204',
    employeNom: 'Boudiaf',
    employePrenom: 'Meriem',
    employeFonction: 'Controleuse de gestion',
    employeDirection: 'Direction Finance',
    intituleFormation: 'Excel avance',
    contexteFormation: 'Amelioration des reportings budgetaires consolidés.',
    objectif: 'Automatiser les tableaux de bord financiers.',
    kpi: 'Reduction du temps de production des reportings.',
    echeance: '2026-09-01',
    ecartMetier: 'Analyse budgetaire.',
    ecartOutils: 'Excel et TCD avances.',
    ecartComportement: '',
    ecartProjet: '',
    dateSignature: '2026-04-15',
    signatureResponsable: 'Amine Kaci',
  },
  'trk-008': {
    responsableNom: 'Hadef',
    responsablePrenom: 'Lina',
    responsableFonction: 'Directrice RH',
    responsableDirection: 'Direction RH',
    employeMatricule: 'RH-9021',
    employeNom: 'Saadi',
    employePrenom: 'Ahlam',
    employeFonction: 'Chargee developpement RH',
    employeDirection: 'Direction RH',
    intituleFormation: 'Gestion de projet',
    contexteFormation: 'Besoin de piloter les chantiers RH transverses avec plus de rigueur.',
    objectif: 'Structurer les jalons et le pilotage des projets RH.',
    kpi: 'Respect des delais sur les projets RH prioritaires.',
    echeance: '2026-07-22',
    ecartMetier: 'Planification projet.',
    ecartOutils: 'Outils de suivi collaboratif.',
    ecartComportement: 'Coordination inter-directions.',
    ecartProjet: 'Projet SIRH 2026.',
    dateSignature: '2026-04-15',
    signatureResponsable: 'Lina Hadef',
  },
  'trk-009': {
    responsableNom: 'Ferhat',
    responsablePrenom: 'Nadia',
    responsableFonction: 'Directrice Est',
    responsableDirection: 'Direction Est',
    employeMatricule: 'EST-6501',
    employeNom: 'Amrani',
    employePrenom: 'Nabil',
    employeFonction: 'Chef de zone',
    employeDirection: 'Direction Est',
    intituleFormation: 'Leadership',
    contexteFormation: 'Encadrement de nouvelles equipes regionales.',
    objectif: 'Accompagner les managers de proximite dans le pilotage des equipes.',
    kpi: 'Amelioration du suivi des objectifs terrain.',
    echeance: '2026-06-30',
    ecartMetier: 'Management de proximite.',
    ecartOutils: 'Tableaux de suivi commercial.',
    ecartComportement: 'Delegation.',
    ecartProjet: '',
    dateSignature: '2026-04-14',
    signatureResponsable: 'Nadia Ferhat',
  },
  'trk-010': {
    responsableNom: 'Ziani',
    responsablePrenom: 'Karim',
    responsableFonction: 'Responsable formation',
    responsableDirection: 'Direction Ouest',
    employeMatricule: 'O-9975',
    employeNom: 'Mekki',
    employePrenom: 'Yacine',
    employeFonction: 'Superviseur agence',
    employeDirection: 'Direction Ouest',
    intituleFormation: 'Communication efficace',
    contexteFormation: 'Ameliorer la coordination entre agences et encadrement.',
    objectif: 'Fluidifier les echanges et la remontée d’information.',
    kpi: 'Baisse des incidents de communication interne.',
    echeance: '2026-08-18',
    ecartMetier: 'Pilotage d’équipe.',
    ecartOutils: 'Supports de communication.',
    ecartComportement: 'Ecoute active.',
    ecartProjet: '',
    dateSignature: '2026-04-14',
    signatureResponsable: 'Karim Ziani',
  },
  'trk-012': {
    responsableNom: 'Rahal',
    responsablePrenom: 'Imane',
    responsableFonction: 'Directrice commerciale',
    responsableDirection: 'Direction Commerciale',
    employeMatricule: 'C-6310',
    employeNom: 'Hadji',
    employePrenom: 'Sara',
    employeFonction: 'Superviseure vente',
    employeDirection: 'Direction Commerciale',
    intituleFormation: 'Leadership',
    contexteFormation: 'Besoin de standardiser les pratiques d’encadrement en agences.',
    objectif: 'Renforcer la conduite d’equipe et l’animation des rituels managériaux.',
    kpi: 'Hausse de la productivite des equipes commerciales.',
    echeance: '2026-06-25',
    ecartMetier: 'Management de la performance.',
    ecartOutils: 'Outils CRM.',
    ecartComportement: 'Leadership situationnel.',
    ecartProjet: '',
    dateSignature: '2026-04-13',
    signatureResponsable: 'Imane Rahal',
  },
}

export function getStoredTrackingRows() {
  const raw = localStorage.getItem(TRACKING_ROWS_STORAGE_KEY)
  if (!raw) return initialTrackingRows

  const storedRows = JSON.parse(raw)
  const storedIds = new Set(storedRows.map((row) => row.id))
  const missingSeedRows = initialTrackingRows.filter((row) => !storedIds.has(row.id))

  return [...storedRows, ...missingSeedRows]
}

export function saveTrackingRows(rows) {
  localStorage.setItem(TRACKING_ROWS_STORAGE_KEY, JSON.stringify(rows))
}

export function getStoredFormStates() {
  const raw = localStorage.getItem(FICHE_FORMS_STORAGE_KEY)
  if (!raw) return initialFormStates

  const storedForms = JSON.parse(raw)
  return {
    ...initialFormStates,
    ...storedForms,
  }
}

export function saveFormStates(forms) {
  localStorage.setItem(FICHE_FORMS_STORAGE_KEY, JSON.stringify(forms))
}

export function getStoredNotifications() {
  const raw = localStorage.getItem(FICHE_NOTIFICATIONS_STORAGE_KEY)
  return raw ? JSON.parse(raw) : []
}

export function saveNotifications(notifications) {
  localStorage.setItem(FICHE_NOTIFICATIONS_STORAGE_KEY, JSON.stringify(notifications))
}
